# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: readthedocs/mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-24.04
  tools:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    python: "3.11"
=======
    python: 3.7
>>>>>>> 258394e26 ([Meta] Hopefully fix readthedocs building (#10244))
=======
    python: "3.7"
>>>>>>> 7b9553440 ([Meta] RTD version must be a string (#10245))
=======
    python: "3.11"
>>>>>>> 6ea4c1285 ([test] readthedocs python 3.11 and schdule test - main (#10247))

python:
  install:
      - requirements: readthedocs/requirements.txt

# Optionally build your docs in additional formats such as PDF and ePub
formats: []
